services:

  frontend:
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    build:
      context: ./frontend

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - db_data:/data/db

volumes:
  db_data:
    driver: local