services:
    api:
      working_dir: /usr/src/app
      ports:
        - "8080:8080"
      env_file:
      - .env.local
      volumes:
        - ./api:/usr/src/app
      build:
        context: ./api
      depends_on:
        - mongo

    # frontend:
    #   working_dir: /usr/src/app
    #   ports:
    #     - "3000:3000"
    #   environment:
    #     NODE_ENV: development
    #   volumes:
    #     - ./frontend:/usr/src/app
    #   build:
    #     context: ./frontend
    
    redisinsight:
        image: redis/redisinsight:2.70
        ports:
          - "5540:5540"

    redis:
        image: redis:8.0.2-alpine
        ports:
            - "6379:6379"

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./db_data:/data/db
volumes:
    db_data:
        driver: local
